version: "3.8"

services:
  civigo-citizen:
    image: node:20-alpine
    working_dir: /app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      HOSTNAME: 0.0.0.0
      PORT: 3000
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL:-http://localhost:54321}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    volumes:
      - ./apps/civigo-citizen:/app
      - citizen_node_modules:/app/node_modules
    command: sh -c "npm ci && npm run dev"

  civigo-gov:
    image: node:20-alpine
    working_dir: /app
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      HOSTNAME: 0.0.0.0
      PORT: 3001
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL:-http://localhost:54321}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      RESEND_API_KEY: ${RESEND_API_KEY}
    volumes:
      - ./apps/civigo-gov:/app
      - gov_node_modules:/app/node_modules
    command: sh -c "npm ci && npm run dev"

volumes:
  citizen_node_modules:
  gov_node_modules:
