export const adminStrings = {
  appTitle: "Civigo Admin",
  nav: {
    dashboard: "Dashboard",
    departments: "Departments",
    officers: "Officers",
    logout: "Logout",
  },
  departments: {
    title: "Departments",
    newDepartment: "New Department",
    editDepartment: "Edit Department",
    deleteConfirmTitle: "Delete Department",
    deleteConfirmDesc: "This action cannot be undone.",
    code: "Code",
    name: "Name",
    create: "Create",
    save: "Save",
    delete: "Delete",
    created: "Department created",
    updated: "Department updated",
    deleted: "Department deleted",
  },
  officers: {
    title: "Officers",
    addOfficer: "Add Officer Profile",
    assignDepartment: "Assign Department",
    fullName: "Full name",
    email: "Email",
    assign: "Assign",
    activate: "Activate",
    deactivate: "Deactivate",
    created: "Officer profile added",
    assigned: "Department assigned",
    toggled: "Assignment updated",
  },
  pager: { previous: "Previous", next: "Next", pageSize: "Page size" },
  errors: {
    unknown: "Something went wrong",
    unique: "Already exists",
    hasDependencies: "Department has dependent data",
  },
};
